version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    container_name: gym-app-postgres
    environment:
      POSTGRES_DB: gym_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./gym-app-database:/docker-entrypoint-initdb.d
      - gym-app-backend_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
    networks:
      - gym-app-network

  backend:
    build: .
    container_name: gym-app-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: gym_app
      DB_USER: postgres
      DB_PASSWORD: postgres
      PORT: 3000
      JWT_SECRET: supersecretkey
    networks:
      - gym-app-network

volumes:
  gym-app-backend_postgres_data:

networks:
  gym-app-network:
    driver: bridge
