version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gym-app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gym_app_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./gym-app-database:/docker-entrypoint-initdb.d
    networks:
      - gym-app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: gym-app-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gymapp.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - gym-app-network

volumes:
  postgres_data:

networks:
  gym-app-network:
    driver: bridge
